#!/usr/bin/ruby

$:.unshift(File.join(File.dirname(__FILE__), "..", "lib"))
require "igc"

def main(argv)
  argv.each do |arg|
    File.open(arg) do |file|
      igc = IGC.new(file)
      unless igc.unknowns.empty?
        puts("# #{arg}")
        puts(igc.unknowns.join("\n"))
      end
    end
  end
end

main(ARGV) if $0 == __FILE__
