#!/usr/bin/ruby

$:.unshift(File.join(File.dirname(__FILE__), "..", "lib"))
require "igc"
require "ostruct"
require "optparse"
require "photo"

TIME_REGEXP = /\A([+\-])?([0-9]|1[01])(?::([0-5][0-9]))?\z/

def main(argv)
  hints = OpenStruct.new
  hints.photo_tz_offset = 0
  hints.tz_offset = 0
  OptionParser.new do |op|
    op.on("-p", "--photo-tz-offset OFFSET", TIME_REGEXP, "Photo timezone offset") do |arg|
      hints.photo_tz_offset = (60 * arg[2].to_i + arg[3].to_i) * (arg[1] == "-" ? -60 : 60)
    end
    op.on("-z", "--tz-offset OFFSET", TIME_REGEXP, "Timezone offset") do |arg|
      hints.tz_offset = (60 * arg[2].to_i + arg[3].to_i) * (arg[1] == "-" ? -60 : 60)
    end
    op.parse!(argv)
  end
  argv.each do |arg|
    case arg
    when /\.igc/i
      igc = IGC.new(File.open(arg))
      puts([igc.fixes[0].time + hints.tz_offset, arg].join("\t"))
      puts([igc.fixes[-1].time + hints.tz_offset, arg].join("\t"))
    else
      photo = Photo.new(arg)
      puts([photo.time + hints.photo_tz_offset - hints.tz_offset, arg].join("\t"))
    end
  end
end

main(ARGV) if $0 == __FILE__
